### ISSUE TITLE
List<ImageMarker> problem

### ISSUE THREAD

**Issue by ruralkan** [tillnagel/unfolding#105]
Hi

I tried to make make a List of ImageMarkers:
List<ImageMarker> stations = new ArrayList<ImageMarker>();
so, when I use the method map.addMarkers(stations) , processing say me:
the method not is applicable for arguments List<ImageMarker>

Is There some option to use map.addMarkars with List<ImageMarker>

**Comment by tillnagel** [comment]
In your e-mail you clarified that you are trying to use ```List<ImageMarker>```. However, the ```map.addMarker()``` method expects ```List<Marker>``` as parameter. Thus, you have to use the following:

```
List<Marker> stations = new ArrayList<ImageMarker>();
// .. populate list
map.addMarkers(stations);
```

**Comment by ruralkan** [comment]
When I try to use, I have this

Cannot convert from ArrayList<ImageMarker> to List<Marker>

but I use a for cicle:

for(int i = 0; i <estaciones.size(); i++) {
  
  map.addMarkers(estaciones.get(i));
  
 }

It is work!!!
Thanks I upload the sketch when I finish :D

**Comment by eduzal** [comment]
you'll probably have to cast the ArrayList as a List.

**Comment by tillnagel** [comment]
@ruralkan Closing it. Let me know if you have further troubles.
