### ISSUE TITLE
MarkerFactory: possibility to use another class than MultiMarker

### ISSUE THREAD

**Issue by FogiaFr** [tillnagel/unfolding#115]
In the MarkerFactory, SimplePointMarker, SimpleLineMarker and SimplePolygonMarker can be overwritten with the setXXXClass but the MultiMarker can't.

A possible way to do this can be found there:
https://github.com/FogiaFr/eu/blob/master/front/eu-front-client/src/main/java/com/mkl/eu/front/client/map/marker/MarkerFactory.java
The changes are:
- addition of a Constructor to MultiMarker with a List<Marker>
- modification of the constructor of the MarkerFactory 
- addition of a setMultiPolygonClass method 
- modification of the createMultiMarker method

**Comment by tillnagel** [comment]
Thanks, interesting idea.

Can you say a bit more about why you need this, or how you are using it? (Not so much about the implementation, but on your intended usage). For now, we see the MultiMarker simply as a composite.

**Comment by FogiaFr** [comment]
I am developping a game that used a Map (the World Map) and the map is divided in provinces. Some provinces are MultiPolygon (for example, Scotland and the nearby islands or provinces that are in the 'normal' map and in zoom focus map).
And since I use my markers (I extends the Marker class but I need a custom class to handle some events like drag and drop of counters for example), I need to have an implementation for MultiMarker.

**Comment by tillnagel** [comment]
Thanks @FogiaFr for the suggestion. See [MultiMarkerTestApp.java](https://github.com/tillnagel/unfolding/blob/27e6b169c3cf3ac3d2fb2fa12568f66985e115e8/test/de/fhpotsdam/unfolding/data/custommulti/MultiMarkerTestApp.java) for an example, as I implemented it a bit simpler than in your implementation. Let me know if that is not sufficient.
