### ISSUE TITLE
Why so little doc explanation for the unfolding.geo package? 

### ISSUE THREAD

**Issue by QuantumShen** [tillnagel/unfolding#124]
By the way, is there API that can transform km distance to pixels on the map? Thank you.

**Comment by tillnagel** [comment]
Yes, it's a bit under documented. However, that package mostly is for internal use. Do you have something special in mind?

Maybe you are more looking for the GeoUtils class in the utils package? There you'll also find helper methods to convert km to pixels and vice verse. Specifically, check out `GeoUtils.getDestinationLocation(originLocation, bearing, distanceInKm)` for your question.

**Comment by tillnagel** [comment]
For a full example to use that method for calculating km to pixels, see https://github.com/tillnagel/unfolding/blob/master/examples/de/fhpotsdam/unfolding/examples/geo/GetDistanceApp.java

**Comment by QuantumShen** [comment]
You are so talented and willing to help! Thank you.
