### ISSUE TITLE
how to use Unfoldingmap with JavaFX

### ISSUE THREAD

**Issue by RnoldR** [tillnagel/unfolding#125]
Is there a way to create a map with a javaFX environment. I tried several solution but could not find a working solution, maybe somebody has something that works?

**Comment by RnoldR** [comment]
Does the closing of this question mean that there is an answer which I seem to have missed, or that you just will not solve it?

**Comment by tillnagel** [comment]
Sorry, I should have made a comment. 

This is not an issue, but a question, to which I do not have an answer. And as nobody else chimed in I closed it, now. You might want to ask this question on the Processing forums or on other outlets.

**Comment by RnoldR** [comment]
Thanks for you elaboration and direction where I might get an answer. I 
am still interested in integrating a map in my javaFX applications.
