### ISSUE TITLE
GeoJSONReader issue - Bug or something else?

### ISSUE THREAD

**Issue by masterflorin** [tillnagel/unfolding#131]
I've posted all details [here](http://gis.stackexchange.com/questions/195153/json-error-unfolding-library-bug-or-something-else), as I thought somebody might have an idea as I don't know whether is an actual issue.

Not really sure what to think about it as I don't know where the fault comes from.
I'd figure it would be the JSON but it runs fine somewhere else.

Thanks!

**Comment by tillnagel** [comment]
Clearly a bug in Unfolding's JSON parser. Will look into it.

**Comment by tillnagel** [comment]
Mmh, just tested it, and it works for me. Which Unfolding version are you using? Could you try out the latest git version?

**Comment by masterflorin** [comment]
I'm using the 9.6. but downloaded from the website a while ago, not from git but I should try it out.

Wow, that basemap looks pretty nice. Which one is it?

**Comment by tillnagel** [comment]
Yep, please give it a go. There have been two fixes in the GeoJSON parser since 0.9.6.

That's CartoDB's Positron map.

**Comment by masterflorin** [comment]
OK, I cloned the git, then imported it into Eclipse, but now comes a newbie question.
I can't seem to make the files I make run. How do I do that?

**Comment by tillnagel** [comment]
Send me your e-mail address to info@unfoldingmaps.org and I will give you a link to the latest beta.
