### ISSUE TITLE
Server returned HTTP response code: 407

### ISSUE THREAD

**Issue by paul-github** [tillnagel/unfolding#133]
Hi! I am taking right now an [online course](https://www.coursera.org/learn/object-oriented-java) which uses Unfolding Maps. The first assignment is to run a code which displays the given map by the instructors, and draw another map beside the first one. However, the first time I ran the code (not yet modified), nothing was displayed on the applet window, and Eclipse's console printed out these [errors](http://pastebin.com/xQZh4fVV).
 
Because of the error, I tried doing the [introductory tutorial for Eclipse](http://unfoldingmaps.org/tutorials/getting-started-in-eclipse.html) hoping that it would eventually lead me to the solution. However, I also encountered [errors](http://pastebin.com/41eipFEc) during the applet execution. I believe it has something to do with proxy authentication. I already tried setting my 'Active Provider' to 'Manual' and typed the proxy address, port, username and password but still the error occurs. Meanwhile, the fatal error occurs whenever I there is a third parameter for the `size()` in the` setup()` method. This error shows up whenever I terminate the applet window. 

Please help me. I've been searching for the solution for hours but I'm still stuck with the problem. Anyway, if the problem is not from Unfolding Maps, you can disregard this issue. Thank you!

Java Codes:
- [from the course](http://pastebin.com/P8JUt91p)
- [my code](http://pastebin.com/mB4K1dLT)

**Comment by tillnagel** [comment]
This is not a problem with Unfolding Maps, but with your system environment. It seems you are using a computer on a network where you need to setup a web proxy. Either you execute your programs on another computer on a different network, or you'll need to set your Java environment to use a proxy. The settings for that you will get from your network administrators.

**Comment by paul-github** [comment]
Noted. Thank you!
