### ISSUE TITLE
How to run this project in eclipse?

### ISSUE THREAD

**Issue by maoxiaoke** [tillnagel/unfolding#134]
I had refered the website http://unfoldingmaps.org/tutorials/getting-started-in-eclipse.html. But I have a problem to run this Project.

**Comment by tillnagel** [comment]
Would be helpful if you specify which problems you had. Do you think this is a bug? Any specific error message you got?

**Comment by rishikumarreddy** [comment]
The file "http://mt1.google.com/vt/v=w2p.116&hl=de&x=714&y=1654&z=12&s=Galileo" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
this is the problem that i get when i try to open my java applet 
only the background is visible on the applet 
the map is not visible on the screen

**Comment by tillnagel** [comment]
@maoxiaoke never responded, and @rishikumarreddy: please see #100. Closing this.
