### ISSUE TITLE
SimplePointMarker draws incorrect ellipse

### ISSUE THREAD

**Issue by platinumICE** [tillnagel/unfolding#137]
Ellipse drawn by SimplePointMarker draws incorrectly.

Function call pg.ellipse() by default uses **ellipseMode(CORNER)** by default so the ellipse center is drawn off by the value of radius.

Call to pg.ellipse() in draw() should be preceded by call to **pg.ellipseMode(pg.RADIUS);**

**Comment by platinumICE** [comment]
Correction: default is ellipseMode(CENTER), but it should be ellipseMode(RADIUS), otherwise the size of the marker is wrong (twice as small), not the position.

**Comment by tillnagel** [comment]
Can you give an example on why you think the size of the marker is wrong? ellipseMode(CENTER) is Processing's default.

**Comment by platinumICE** [comment]
[sketch_160829a.txt](https://github.com/tillnagel/unfolding/files/442263/sketch_160829a.txt)

Here is an example sketch. If you use ellipseMode(CENTER), then don't call this attribute radius, it should be called diameter. This is especially apparent when you try getHitMarkers(). In the sketch red circle is drawn by marker with radius = 200px. Black circle is drawn manually with ellipse command, ellipseMode = RADIUS and radius = 200px. 

If you click the map "Marker is hit\missed" is displayed in output via getHitMarkers(). Watch how hit area actually covers black circle area, not only the red one.
