### ISSUE TITLE
Rotation event

### ISSUE THREAD

**Issue by Driezzz** [tillnagel/unfolding#138]
Is there a way to add a rotation event like how you added the other two events (pan and zoom)? And with the rotation, rotate your map and update the Compass direction?

`eventDispatcher.register(map, "zoom");`
`eventDispatcher.register(map, "??rotation/rotate??");`

**Comment by tillnagel** [comment]
No, that is not possible. You either provide multitouch interaction (see [MultitouchMapApp](https://github.com/tillnagel/unfolding/blob/master/examples/de/fhpotsdam/unfolding/examples/interaction/multitouch/MultitouchMapApp.java) example), or do it programmatically (via `map.rotate(..)`. After registering a CompassUI to a map, it updates automatically.
