### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by JamesPwi** [tillnagel/unfolding#146]
do i know how i can run this inside sketch  processing language ?

**Comment by tillnagel** [comment]
Can you be more specific what you are trying to do?

Unfolding Maps is aimed to work directly within the Processing IDE, as well as a Java library (with other IDEs such as Eclipse or similar). However, the current release is not for Processing 3 anymore. If you want to get access to the beta (for P3) let me know and send us an e-mail.

**Comment by JamesPwi** [comment]
i am using processing 2.2.1 version but for me clearMarkers and removeMarkers command is not working for me  , no idea why so ?

**Comment by tillnagel** [comment]
Please provide a short code example of what you try to do, and where it exactly fails. (Here: how do you try to use clearMarkers, and which class do you use?)

**Comment by JamesPwi** [comment]
sorry  today  i make one project but in that clearmarker is not working but now i created one and its working perfectly. maybe i did something wrong at that time.

here is my code :

[import de.fhpotsdam.unfolding.mapdisplay.*;
import de.fhpotsdam.unfolding.utils.*;
import de.fhpotsdam.unfolding.marker.*;
import de.fhpotsdam.unfolding.marker.SimpleLinesMarker;
import de.fhpotsdam.unfolding.tiles.*;
import de.fhpotsdam.unfolding.interactions.*;
import de.fhpotsdam.unfolding.ui.*;
import de.fhpotsdam.unfolding.*;
import de.fhpotsdam.unfolding.core.*;
import de.fhpotsdam.unfolding.mapdisplay.shaders.*;
import de.fhpotsdam.unfolding.data.*;
import de.fhpotsdam.unfolding.geo.*;
import de.fhpotsdam.unfolding.texture.*;
import de.fhpotsdam.unfolding.events.*;
import de.fhpotsdam.utils.*;
import de.fhpotsdam.unfolding.providers.*;
import de.fhpotsdam.unfolding.marker.Marker;
import de.fhpotsdam.unfolding.marker.MarkerManager;



UnfoldingMap map;
SimplePointMarker berlinMarker,dublinMarker;
MarkerManager<Marker> markerManager;
 
void setup() {
  size(800, 600);
 
  map = new UnfoldingMap(this , new Microsoft.AerialProvider());
  MapUtils.createDefaultEventDispatcher(this, map);
  markerManager = map.getDefaultMarkerManager();
 
 Location berlinLocation = new Location(52.5, 13.4);
 Location dublinLocation = new Location(53.35, -6.26);
  berlinMarker = new SimplePointMarker(berlinLocation);
  dublinMarker = new SimplePointMarker(dublinLocation);
  
  markerManager.addMarker(berlinMarker);
  markerManager.addMarker(dublinMarker);
}
 
void draw() {
  map.draw();
  
  ScreenPosition berlinPos = berlinMarker.getScreenPosition(map);
  ScreenPosition dublinPos = dublinMarker.getScreenPosition(map);
  strokeWeight(16);
  stroke(67, 211, 227, 100);
  //noFill();
  //ellipse(berlinPos.x, berlinPos.y, 36, 36);
  strokeWeight(16);
  stroke(67, 211, 227, 100);
  //noFill();
  //ellipse(dublinPos.x, dublinPos.y, 36, 36);
}

void keyPressed() {
    if (key == 'r') {
      markerManager.removeMarker(berlinMarker);
    }
    if (key == 'a') {
      markerManager.addMarker(berlinMarker);
    }
    if (key == 'c') {
      markerManager.clearMarkers();
    }
}

**Comment by JamesPwi** [comment]
hello @tillnagel  ,   can you pass me some information on markers , like i have created markers using mouse click but  now i want to make something  like   i want  markers to be selected and then  when i want to delete them i can delete them too and i even make it like a path follower like 1 is link to 2 and 2 to 3 and 2 to 4 but suppose if i want to delete marker 3 and when i delete it i want my marker 2 to link with 4  so that path is always working. can you help me with this ?

**Comment by tillnagel** [comment]
This does not seem to be an issue anymore (or, at least, a new one). 

Best would be to be be more specific, provide sample code and/or graphics to explain what you are trying to do, and post it to the Processing forum on 3rd party libraries.
