### ISSUE TITLE
Json not running

### ISSUE THREAD

**Issue by paulobenson** [tillnagel/unfolding#149]
I'm trying to run something like your metro lines exemple.
But it's not showing the lines it self. I tests the geoJson at the geoJson.io. And it works.
I don't know if it's because it's a lot of lines.
but the program run slower than without the GeoJson part, but it doesn't show any lines!

import de.fhpotsdam.unfolding.*;
import de.fhpotsdam.unfolding.geo.*;
import de.fhpotsdam.unfolding.utils.*;
import de.fhpotsdam.unfolding.providers.*;
import de.fhpotsdam.unfolding.data.*;
import de.fhpotsdam.unfolding.marker.*;
import java.util.List;

color col = color(#F4FC14);

Location sampaLocation = new Location(-23.54f, -46.63f);

UnfoldingMap map;

void setup() {
  size(1280,720);
  smooth();
  
  map = new UnfoldingMap(this);
  MapUtils.createDefaultEventDispatcher(this,map);
  map.zoomAndPanTo(sampaLocation, 12); // regiao inicial e zoo inicial  
  float maxPanningDistance = 30; // em Km
  map.setPanningRestriction(sampaLocation,maxPanningDistance); 
  map.setZoomRange(12, 15);
  map.setTweening(true);
  
  List<Feature> linhasOnibus = GeoJSONReader.loadData(this, "data/teste.geojson");
  
   List<Marker> linhasMarkers = new ArrayList<Marker>();
  for (Feature feature : linhasOnibus) {
    ShapeFeature lineFeature = (ShapeFeature) feature;

    SimpleLinesMarker m = new SimpleLinesMarker(lineFeature.getLocations());
    m.setColor(col);
    m.setStrokeWeight(5);
    linhasMarkers.add(m);
  }

  map.addMarkers(linhasMarkers);
}

void draw() {
  map.draw();

}

[teste.geojson.zip](https://github.com/tillnagel/unfolding/files/952850/teste.geojson.zip)

**Comment by tillnagel** [comment]
I assume you are using the beta for P3? It does not support the default renderer Java2D. Please switch to P2D or P3D (`size(1280, 720, P2D);`)

**Comment by paulobenson** [comment]
Thanks man!
It works!
