### ISSUE TITLE
Ereur in !!

### ISSUE THREAD

**Issue by dhiaa05** [tillnagel/unfolding#150]
hello
what is the Erreur in side image
how to solved!!
![problem](https://user-images.githubusercontent.com/29708536/27542473-a340f664-5a87-11e7-838f-1bf1d2fbfa32.jpg)

**Comment by tillnagel** [comment]
Duplicate of #100.

Work-around: Use another map provider, or send us an e-mail to ask for Unfolding beta for Processing 3.

**Comment by dhiaa05** [comment]
thank you!! solved
but what is the importance of processing 3!!

**Comment by tillnagel** [comment]
It is a newer version of Processing. See http://processing.org for more infos.
