### ISSUE TITLE
error!!

### ISSUE THREAD

**Issue by dhiaa05** [tillnagel/unfolding#151]
hello
the programme run Normal for 5 minutes, but Suddenly stoped
how i can fixed the Error and thanx 
![error](https://user-images.githubusercontent.com/29708536/27581248-7809f09e-5b2d-11e7-9823-c47ed5b92e36.jpg)

**Comment by tillnagel** [comment]
Please note, that all map providers are only for educational purposes. Check the terms and conditions of the various providers. In this case, I assume, you requested too many tiles in a too short amount of time. (403 means forbidden).
