### ISSUE TITLE
How can I download the Unfolding API

### ISSUE THREAD

**Issue by eialbur** [tillnagel/unfolding#154]
I have a URL to get to it, but often work offline.

**Comment by tillnagel** [comment]
Can you be more specific? Do you mean to use offline map tiles? Unfolding Maps is a library to help you integrate interactive maps into your Processing app, not a map provider.

It is, however, possible to use offline map tiles. See the https://github.com/tillnagel/unfolding/blob/master/examples/de/fhpotsdam/unfolding/examples/provider/MBTilesMapApp.java example. Unfortunately, to create MBTiles you have to find legacy software TileMill for your OS.

**Comment by eialbur** [comment]
Sorry - part of my question was in the title. I want to download the Unfolding API so that I can do development offline.

**Comment by tillnagel** [comment]
Do you mean the online documentation?

**Comment by eialbur** [comment]
Yes, I want to download the API javadocs
