### ISSUE TITLE
getScreenPosition of a path made by SimpleLinesMarker

### ISSUE THREAD

**Issue by Dazzid** [tillnagel/unfolding#157]
Hi,
I'm just trying to have the pixels coordinates of a path that was build by SimpleLinesMarker m = new SimpleLinesMarker(lineFeature.getLocations()). 
I'm using something like this:
```
    List<Marker> myMarker;
    myMarker = map.getMarkerManager(0).getMarkers();
    for (int i = 0; i < myMarker.size(); i++) {
      println(map.getScreenPosition(myMarker.get(i).getLocation()));
    }
```

But it is not the correct way to do so, it gives back far away pixel coordinates among many [0,0]
return:
[ 0.0, 0.0, 0.0 ]
[ -8063.0, 195758.0, 0.0 ]
[ 0.0, 0.0, 0.0 ]
[ -10058.0, 247856.0, 0.0 ]
[ 0.0, 0.0, 0.0 ] 
...

**Comment by tillnagel** [comment]
Can you specify which Processing and Unfolding versions you are using? 
Also, which renderer to you use? (the one specified in `size()`)

**Comment by Dazzid** [comment]
Hey Till,
It is Processing 3.3.6 with Unfolding 0.9.9. And P2D

**Comment by tillnagel** [comment]
If you want to get the screen positions for all locations of a line marker you need to access the actual locations, like so:

`
    List<Marker> myMarkers = map.getMarkerManager(0).getMarkers();
    for (int i = 0; i < myMarkers.size(); i++) {
    	SimpleLinesMarker myMarker = (SimpleLinesMarker) myMarkers.get(i);
    	for (int j = 0; j < myMarker.getLocations().size(); j++) {
    		println(map.getScreenPosition(myMarker.getLocation(j)));
    	}
    }
`

The marker.getLocation() does return the centroid for all shape markers. This might be a bug for the SimpleLineMarker. Let me know if this centroid is what you are interested in.

**Comment by tillnagel** [comment]
For getting the correct centroid, you can use this as a work-around:

```
    Location centroid = GeoUtils.getEuclideanCentroid(connectionMarker.getLocations());
    ScreenPosition pos = map.getScreenPosition(centroid);
```

**Comment by Dazzid** [comment]
Now it make sense. Thanks!

**Comment by tillnagel** [comment]
Which was it you needed? Centroid? Or all locations?
