### ISSUE TITLE
How to deactivate panning when moving an external slider?

### ISSUE THREAD

**Issue by Dazzid** [tillnagel/unfolding#159]
Hi Till,
This might be a very simple question, but I don't find the answer using the processing examples.
After just adding a simple slider, I would need to deactivate the panning to prevent the map to move while controlling some parameters in the GUI. This might be related to MouseHandler but looking into the reference, it is not clear to me how to deactivate it.
Thanks for the help

**Comment by tillnagel** [comment]
Did you see https://github.com/tillnagel/unfolding/commit/b5729dbe08cfcd719b3201fac8d2dd9ebea03cf5 ?
