### ISSUE TITLE
Geo-location at mouse position

### ISSUE THREAD

**Issue by skatewizard** [tillnagel/unfolding#162]
Hello! How do I get more precise geo-location on mouse position? 

 // Shows geo-location at mouse position
  Location location = map.getLocation(mouseX, mouseY);
  text(location.toString(), mouseX, mouseY);

When I zoom in on the map I need more precise numbers than example "52.131"...

Thanks!

**Comment by tillnagel** [comment]
You can directly access the values via `location.getLat()` and `location.getLon()` instead of relying on the toString() method which only shows three digits.
