### ISSUE TITLE
zoomAndPanTo goes around in circles

### ISSUE THREAD

**Issue by davidbambalan** [tillnagel/unfolding#164]
Writing `zoomAndPanTo();` in `draw()` pans the map in circles. Is there a way I can change the location dynamically through code and not hard-coding it?

**Comment by tillnagel** [comment]
Can you be more specific, or give an example on what you are trying to achieve?

What do you mean by "pans the map in circles"? zoomAndPanTo() zooms to the specified level, and pans to the specified location.

**Comment by davidbambalan** [comment]
How do I pan the map according to the location of the GPS sensor I'm using?

**Comment by davidbambalan** [comment]
Does the `getLocation(float x, float y)` still work?

**Comment by tillnagel** [comment]
Still not fully sure what you are trying to do.

But if you simply want to convert geo-locations to screen coordinates check out the `SimpleConversionMapApp` and if you want to pan the map to a location then check out the `PanAnimationMapApp` example.
