### ISSUE TITLE
How to style markers with geoJSON and CSV

### ISSUE THREAD

**Issue by SebastianHaiduk** [tillnagel/unfolding#166]
Hi Guys,

so I am working on project, and I am using Unfolding.
I am trying to add markers from a geoJSON file on the map. This is working fine. But now i want style those markers based on values from an csv datasheet. I have no idea how or if this is possible.

I only used this command:

List<Feature> countries = GeoJSONReader.loadData(this, "stationen.geojson");
  List<Marker> countryMarkers = MapUtils.createSimpleMarkers(countries);
  map.addMarkers(countryMarkers);
Maybe some can help me, thank you in advance

Sebastian

**Comment by tillnagel** [comment]
You can simply iterate over all creates markers and style them, e.g.

```
for (Marker marker : countryMarkers) {
	marker.setStrokeColor(color(255, 0, 0));
}
```

For more customiaztion, check out this [example](https://github.com/tillnagel/unfolding/tree/master/examples/de/fhpotsdam/unfolding/examples/data/styled) showing how to load GeoRSS data and use your own custom markers, which you can draw in any way.

Hope this is still useful for you.
