### ISSUE TITLE
The Map canvas is shifted in the application window when using an OpenGL renderer

### ISSUE THREAD

**Issue by saesols** [tillnagel/unfolding#168]
The map canvas is shifted in the application window when using an OpenGL renderer. 

`size(800, 600, OPENGL);`

[screenshot #1](https://yadi.sk/i/2M0gU8u27bWUFg)

Warnings with OpenGL:

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/C:/Users/Alex/Desktop/JavaOOP/TestFolding/lib/gluegen-rt.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Unfolding Map v0.9.6
Using OpenGLMapDisplay with processing.opengl.PGraphics3D`

Without specifying an "OpengGL" renderer  - canvas is in place but an image becomes blurry. 

`size(800, 600);`

[screenshot #2](https://yadi.sk/i/jXfYnhv9R5F6Gw)

Code: default HelloUnfoldingWorld from Unfolding repo. 
Unfolding map v.0.9.6
OS: Windows 10 with latest update
GPU: Asus GeForce GTX 1060 Ti 6GG VRAM
IDE:  IDEA

**Comment by tillnagel** [comment]
Thanks for the pointer. The warning seems to be a problem with JOGL and the latest Java version. Not sure if it is related. I did not find anything related (JOGL, OpenGL, Windows, etc) in the Processing forums nor elsewhere. Alas, I cannot reproduce on Mac OS.

Could you try out the latest Unfolding beta 0.9.92? 

Find the beta of Unfolding for Processing 3+ for Java IDEs at
http://services.informatik.hs-mannheim.de/~nagel/GDV/unfolding_app_template_with_examples_0.9.92.zip
or use the Processing IDE app template at
http://services.informatik.hs-mannheim.de/~nagel/GDV/Unfolding_for_processing_0.9.92.zip

**Comment by saesols** [comment]
On 0.9.92 with Java 12.0.2 everything works fine.
