### ISSUE TITLE
How to add image in marker

### ISSUE THREAD

**Issue by darkknight377** [tillnagel/unfolding#180]

**Comment by tillnagel** [comment]
Did you see the ImageMarker example? Is that what you need? https://github.com/tillnagel/unfolding/blob/master/examples/de/fhpotsdam/unfolding/examples/marker/imagemarker/ImageMarkerApp.java

**Comment by tillnagel** [comment]
(If not, please reopen this issue)

**Comment by darkknight377** [comment]
thank you it worked!

**Comment by darkknight377** [comment]
One more question though,
How to show text over the image it overlapse with image
