### ISSUE TITLE
How to make the World Map "Round"

### ISSUE THREAD

**Issue by ventildeckeldichtung** [tillnagel/unfolding#184]
Hi, 
for my Map Application I would like to have a World map in which one can move like on Google Maps, meaning, If for example I keep scrolling to the east, I don't want to see the end of the map but instead the beginning of the map from the west. Is there any way to do this?
I hope you can help me, and thanks in advance.

**Comment by tillnagel** [comment]
Unfortunately, this is not supported by Unfolding.
