### ISSUE TITLE
Centroid of polygon leans towards many vertices.

### ISSUE THREAD

**Issue by tillnagel** [tillnagel/unfolding#47]
Currently, the centroid of a set of locations/vertices tends to move towards borders where many vertices are defined. This is due to the algorithm ("minimizes the sum of squared Euclidean distances between itself and each point in the set").

We need to calculate the correct centroid of a polygon.

Red circle indicates the centroid currently calculated by Unfolding. Green shows the correct centroid.

![Centroid map example](http://i.imgur.com/DcPTF.png)

**Comment by gdad-s-river** [comment]
Is this something similar to 

https://github.com/Mapbox/polylabel ? ( Medium post: http://bit.ly/mapbox-visual-centre )

**Comment by tillnagel** [comment]
Thanks @gdad-s-river. This has been fixed since a while. See GeoUtils#getCentroid
