### ISSUE TITLE
Resizing MaskedGLGraphicsMapDisplay

### ISSUE THREAD

**Issue by RickWalker** [tillnagel/unfolding#55]
Repeated calls to MaskedGLGraphicsMapDisplay seem to leak memory somewhere. This should be reproducible in the example at:
https://github.com/tillnagel/unfolding/blob/master/examples/de/fhpotsdam/unfolding/examples/misc/ResizableMapApp.java
if you resize the window a number of times (c. 10 with default heap size). 

Increasing heap size delays the occurrence of problem but doesn't fix it.

**Comment by tillnagel** [comment]
Apparently fixed since moving to P2 (and new OpenGL renderer).
