### ISSUE TITLE
Maps always have black Background with Java2D-Renderer

### ISSUE THREAD

**Issue by mrieser** [tillnagel/unfolding#93]
The example "Overlaying two maps" from http://unfoldingmaps.org/tutorials/multi-maps.html seems not to work with the latest version (0.9.6). I only get to see the second map, partially dimmed.
I observed the behaviour as well when experimenting with custom tile servers that return png-tiles with transparency. Whatever I draw before I call `map.draw()` is hidden behind a black wall, even if the tiles are all transparent.
I tried to first call `map.setBackgroundColor(null)`, but this did not help.
It works when I specify that the OpenGL-Renderer should be used by Processing. But I think it would be great to have this also for the Java2D-Renderer if possible.

**Comment by tillnagel** [comment]
See #114
